<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>72252612-ce70-47e9-8892-61fd8427bb24</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.NodeJS.Extensions" />
  </ItemGroup>

</Project>
