<Project>

  <!-- 🌍 Global settings -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DoyepAnalyzerUserSecretsId>b0c1b94d-34a6-459e-9765-9ae81e53ee13</DoyepAnalyzerUserSecretsId>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- 🔍 Quality -->
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>

    <!-- 🧹 Build -->
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <!-- 📦 Analyzers -->
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" PrivateAssets="all" />
  </ItemGroup>

</Project>
